{{- if .Values.certManager.enabled -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.clusterIssuer.name }}
spec:
  {{- if eq .Values.certManager.clusterIssuer.type "letsencrypt-staging" }}
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Values.certManager.clusterIssuer.email }}
    privateKeySecretRef:
      name: {{ .Values.certManager.clusterIssuer.name }}-account-key
    solvers:
    - http01:
        ingress:
          class: {{ .Values.ingress.className }}
  {{- else if eq .Values.certManager.clusterIssuer.type "letsencrypt-prod" }}
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.certManager.clusterIssuer.email }}
    privateKeySecretRef:
      name: {{ .Values.certManager.clusterIssuer.name }}-account-key
    solvers:
    - http01:
        ingress:
          class: {{ .Values.ingress.className }}
  {{- else if eq .Values.certManager.clusterIssuer.type "self-signed" }}
  selfSigned: {}
  {{- end }}
{{- end }}