{{- if and .Values.ingress.enabled .Values.certManager.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "webapp.fullname" . }}-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ include "webapp.fullname" . }}-tls
  issuerRef:
    name: {{ .Values.certManager.clusterIssuer.name }}
    kind: ClusterIssuer
  dnsNames:
    {{- range .Values.ingress.hosts }}
    - {{ .host }}
    {{- end }}
{{- end }}